// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYaTD3H5dvwoFnLiQhXWhb07W12yAs4E0',
    appId: '1:2947842542:web:b782fcaed7f56871774eff',
    messagingSenderId: '2947842542',
    projectId: 'meditrack-82c12',
    authDomain: 'meditrack-82c12.firebaseapp.com',
    storageBucket: 'meditrack-82c12.firebasestorage.app',
    measurementId: 'G-QJHKSGLWYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK3avrofXFprpfrpARPRURrV7ku_gPtTs',
    appId: '1:2947842542:android:63fa8ff795c5b558774eff',
    messagingSenderId: '2947842542',
    projectId: 'meditrack-82c12',
    storageBucket: 'meditrack-82c12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsFqhXgbtarAuzVGeqIFnHyiFYoOVdbTw',
    appId: '1:2947842542:ios:2ba91dec9b8293ee774eff',
    messagingSenderId: '2947842542',
    projectId: 'meditrack-82c12',
    storageBucket: 'meditrack-82c12.firebasestorage.app',
    iosBundleId: 'com.example.medTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsFqhXgbtarAuzVGeqIFnHyiFYoOVdbTw',
    appId: '1:2947842542:ios:2ba91dec9b8293ee774eff',
    messagingSenderId: '2947842542',
    projectId: 'meditrack-82c12',
    storageBucket: 'meditrack-82c12.firebasestorage.app',
    iosBundleId: 'com.example.medTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYaTD3H5dvwoFnLiQhXWhb07W12yAs4E0',
    appId: '1:2947842542:web:983f63e935683d55774eff',
    messagingSenderId: '2947842542',
    projectId: 'meditrack-82c12',
    authDomain: 'meditrack-82c12.firebaseapp.com',
    storageBucket: 'meditrack-82c12.firebasestorage.app',
    measurementId: 'G-CL7SVT5ELG',
  );
}
